# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1398ff1e5c6360065e3de324bc6beca39d3689d4564045c9427eb4207ce5d029742b98b7dfdee792c741a35b23371ce97df5d9051b238070117c1d0447a8f496

test:
  secret_key_base: 00024a5bf444f72b138fd234d985eeaba0e813fd12f4df694718694690c56c62be9eacbb3ccddf977aeb5d72cfaacba0ccf8b24c03de1b2455548df47617200b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
